### ISSUE TITLE
How to deploy in real robots?

### ISSUE THREAD

**Issue by happy-my** [JewelryForge/aliengo_deploy#1]
Hi!

Thanks for sharing your work. It's a really good one. I have some questions during real-world implementation.

1. Did you use the onboard computation resources in the Aliengo robot, or did you use another PC?
2. Did you use [unitree_ros_to_real](https://github.com/unitreerobotics/unitree_ros_to_real) and [unitree_ros](https://github.com/unitreerobotics/unitree_ros), or only deploy directly?
3. The joystick is xbox, whether it needs to prepare by myself?

Thanks in advance!

**Comment by JewelryForge** [comment]
1. We use another PC for network inference.
2. We use, of course, [unitree_legged_sdk](https://github.com/unitreerobotics/unitree_legged_sdk) for getting robot states, e.g. joint position;
3. We use a wireless xbox joystick to give a command (linear and angular velocity).

**Comment by happy-my** [comment]
Thanks！
